name: GCN2
loop: true
norm: true

params:
  reddit:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400

  arxiv:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 500
  
  products:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.002
    epochs: 500
  
  reddit:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400

  
  flickr:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400

  yelp:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 500

  cora:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 200

  citeseer:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 200

  pubmed:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 200

  amazoncomputers:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400
  
  amazonphoto:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400
  
  coauthorcs:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400
  
  coauthorphysics:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400
  
  wikics:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400